//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.23 at 04:53:50 AM CEST 
//


package com.rentacar.agentbackend.soap.wsdl;

import com.rentacar.agentbackend.model.CreateGearshiftTypeRequestDTO;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    private final static QName _CreateGearshiftTypeRequest = new QName("http://www.car.com/car", "createGearshiftTypeRequest");
    private final static QName _CreateGearshiftTypeResponse = new QName("http://www.car.com/car", "createGearshiftTypeResponse");
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: agent.soap.gen
     *
     */
    public ObjectFactory() {
    }

    @XmlElementDecl(namespace = "http://www.car.com/car", name = "createGearshiftTypeRequest")
    public JAXBElement<CreateGearshiftTypeRequestDTO> createCreateGearshiftTypeRequest(CreateGearshiftTypeRequestDTO value) {
        return new JAXBElement<>(_CreateGearshiftTypeRequest, CreateGearshiftTypeRequestDTO.class, null, value);
    }

    @XmlElementDecl(namespace = "http://www.car.com/car", name = "createGearshiftTypeResponse")
    public JAXBElement<Long> createCreateGearshiftTypeResponse(Long value) {
        return new JAXBElement<>(_CreateGearshiftTypeResponse, Long.class, null, value);
    }

}
