//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 11:06:49 PM CEST 
//


package com.rentacar.agentbackend.soap.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ad }
     * 
     */
    public Ad createAd() {
        return new Ad();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link CarAccessories }
     * 
     */
    public CarAccessories createCarAccessories() {
        return new CarAccessories();
    }

    /**
     * Create an instance of {@link CarBrand }
     * 
     */
    public CarBrand createCarBrand() {
        return new CarBrand();
    }

    /**
     * Create an instance of {@link CarCarAccessories }
     * 
     */
    public CarCarAccessories createCarCarAccessories() {
        return new CarCarAccessories();
    }

    /**
     * Create an instance of {@link CarClass }
     * 
     */
    public CarClass createCarClass() {
        return new CarClass();
    }

    /**
     * Create an instance of {@link CarModel }
     * 
     */
    public CarModel createCarModel() {
        return new CarModel();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link CreateGearshiftTypeRequestDTO }
     * 
     */
    public CreateGearshiftTypeRequestDTO createCreateGearshiftTypeRequestDTO() {
        return new CreateGearshiftTypeRequestDTO();
    }

    /**
     * Create an instance of {@link FuelType }
     * 
     */
    public FuelType createFuelType() {
        return new FuelType();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

}
